"""Unit tests for the hybrid candidate scorer.

The scorer combines three signals with fixed weights (see SPEC §11):

    score = 0.5 * cosine + 0.3 * fts_rank + 0.2 * boost

Tests use fake embeddings so the cosine values are predictable.
"""

from __future__ import annotations

import math

from core.search import RoomAmenity, SearchFilter
from core.search.score import (
    BOOST_WEIGHT,
    COSINE_WEIGHT,
    FTS_WEIGHT,
    Candidate,
    cosine_similarity,
    score_candidate,
)


class TestCosineSimilarity:
    def test_identical_vectors(self) -> None:
        assert math.isclose(cosine_similarity([1.0, 0.0], [1.0, 0.0]), 1.0)

    def test_orthogonal_vectors(self) -> None:
        assert math.isclose(cosine_similarity([1.0, 0.0], [0.0, 1.0]), 0.0)

    def test_opposite_vectors(self) -> None:
        assert math.isclose(cosine_similarity([1.0, 0.0], [-1.0, 0.0]), -1.0)

    def test_unequal_magnitudes_normalise(self) -> None:
        assert math.isclose(cosine_similarity([2.0, 0.0], [5.0, 0.0]), 1.0)

    def test_zero_vector_returns_zero(self) -> None:
        assert cosine_similarity([0.0, 0.0], [1.0, 1.0]) == 0.0

    def test_length_mismatch_returns_zero(self) -> None:
        # Defensive: we never want a search to crash because one row's
        # embedding was generated by a model with a different dim.
        assert cosine_similarity([1.0, 0.0, 0.0], [1.0, 0.0]) == 0.0


class TestScoreCandidate:
    def test_blend_formula(self) -> None:
        cand = Candidate(
            property_id="p1",
            description_embedding=[1.0, 0.0],
            fts_rank=0.8,
            matched_optional=[RoomAmenity(amenity_name="balcony")],  # one optional hit
            matched_near=["park"],
        )
        score = score_candidate(
            SearchFilter(),
            cand,
            query_embedding=[1.0, 0.0],
        )
        # cosine = 1.0, fts = 0.8, boost = clamp(0.1 + 0.1) = 0.2
        expected = COSINE_WEIGHT * 1.0 + FTS_WEIGHT * 0.8 + BOOST_WEIGHT * 0.2
        assert math.isclose(score, expected)

    def test_missing_embedding_gives_zero_cosine(self) -> None:
        cand = Candidate(
            property_id="p1",
            description_embedding=None,
            fts_rank=0.5,
            matched_optional=[],
            matched_near=[],
        )
        score = score_candidate(SearchFilter(), cand, query_embedding=[1.0, 0.0])
        assert math.isclose(score, FTS_WEIGHT * 0.5)

    def test_missing_query_embedding_gives_zero_cosine(self) -> None:
        cand = Candidate(
            property_id="p1",
            description_embedding=[1.0, 0.0],
            fts_rank=0.5,
            matched_optional=[],
            matched_near=[],
        )
        score = score_candidate(SearchFilter(), cand, query_embedding=None)
        assert math.isclose(score, FTS_WEIGHT * 0.5)

    def test_boost_clamps_at_one(self) -> None:
        # 11 optional hits + 1 near hit would otherwise push boost to 1.2.
        cand = Candidate(
            property_id="p1",
            description_embedding=[1.0, 0.0],
            fts_rank=0.0,
            matched_optional=[RoomAmenity(amenity_name=f"a{i}") for i in range(11)],
            matched_near=["park"],
        )
        score = score_candidate(SearchFilter(), cand, query_embedding=[1.0, 0.0])
        # cosine=1.0, fts=0, boost clamped to 1.0
        expected = COSINE_WEIGHT + BOOST_WEIGHT
        assert math.isclose(score, expected)

    def test_zero_everything_returns_zero(self) -> None:
        cand = Candidate(
            property_id="p1",
            description_embedding=None,
            fts_rank=0.0,
            matched_optional=[],
            matched_near=[],
        )
        assert score_candidate(SearchFilter(), cand, query_embedding=None) == 0.0
