"""
FastAPI application entrypoint.

How to run locally (without Docker):
    uv run uvicorn api.main:app --reload --port 8000

How to run in Docker Compose:
    docker compose up api
    # The app is then reachable at http://localhost:8000

API documentation (auto-generated by FastAPI):
    http://localhost:8000/docs   ← Swagger UI (interactive)
    http://localhost:8000/redoc  ← ReDoc (read-only)

Observability endpoints (Phase 4):
    http://localhost:8000/metrics  ← Prometheus metrics scrape endpoint
    http://localhost:8000/health   ← Liveness check for Docker Compose / load balancers

Application lifecycle:
  startup:  Initialises the ModelRegistry (VLM clients) and creates DB tables.
            Prometheus instrumentation is attached to the app.
            These are stored on `app.state` so routes can access them via Depends().
  shutdown: Disposes the SQLAlchemy engine (closes connection pool).
"""

import logging
import os
from collections.abc import AsyncGenerator
from contextlib import asynccontextmanager

from fastapi import FastAPI
from fastapi.middleware.cors import CORSMiddleware
from prometheus_fastapi_instrumentator import Instrumentator  # type: ignore[import-untyped]

from api.middleware import RequestLoggingMiddleware
from api.routers import images as images_router
from api.routers import models as models_router
from api.routers import properties as properties_router
from api.schemas import HealthResponse
from core.logging_config import setup_logging
from db.session import check_db_connection, create_tables
from models.registry import ModelRegistry

# Configure structured logging BEFORE the first logger.getLogger() call so that
# all subsequent loggers (including uvicorn's) inherit the configured handler.
setup_logging()
logger = logging.getLogger(__name__)


# ── Lifespan ─────────────────────────────────────────────────────────────────
# FastAPI's modern way to run startup/shutdown logic (replaces @app.on_event).
# The `async with` block:
#   - Code before `yield` runs at startup
#   - Code after `yield` runs at shutdown
# The `app` argument lets us store state on `app.state` for dependency injection.


@asynccontextmanager
async def lifespan(app: FastAPI) -> AsyncGenerator[None, None]:
    """
    Manage application startup and shutdown resources.

    Why lifespan instead of @app.on_event?
      @app.on_event("startup") is deprecated in FastAPI 0.93+. The lifespan
      context manager is the official replacement — it's cleaner and supports
      async properly.

    Startup steps:
      1. Create database tables (idempotent — safe to run on every start).
         In production, `alembic upgrade head` (in the Dockerfile CMD) runs instead.
      2. Build the ModelRegistry from environment variables.
         Models that fail to initialise are logged as warnings — the server
         still starts even if, say, Ollama isn't running yet.
    """
    # ── STARTUP ──
    logger.info("Starting up Amenity Detector API...")

    create_tables()

    app.state.model_registry = ModelRegistry.from_env()
    available = app.state.model_registry.available_models()
    logger.info("Model registry ready. Available models: %s", available)

    yield  # Server is running — handle requests here

    # ── SHUTDOWN ──
    logger.info("Amenity Detector API shutting down.")


app = FastAPI(
    title="Amenity Detector API",
    description=(
        "Detect amenities in property images using Vision-Language Models. "
        "Upload images, browse properties, and search by amenity."
    ),
    version="1.0.0",
    lifespan=lifespan,
    docs_url="/docs",
    redoc_url="/redoc",
)

# ── Middleware ────────────────────────────────────────────────────────────────
# Middleware is applied in reverse registration order — CORS wraps everything,
# then RequestLoggingMiddleware logs the final status code.
# (Starlette processes middleware in a stack: last-added = outermost wrapper)

# CORS — allow the Gradio UI (port 7860), the Next.js web frontend (port 3001
# on the host, port 3000 internally inside Docker), and the local FastAPI dev
# tooling to call the API. Override with the `CORS_ORIGINS` env var (comma-
# separated origins, or "*" for permissive dev mode).
_default_origins = [
    "http://localhost:7860",  # Gradio (host)
    "http://localhost:3001",  # Next.js web (host)
    "http://localhost:8000",  # API self / Swagger
    "http://web:3000",        # Next.js web (internal Docker DNS)
    "http://ui:7860",         # Gradio (internal Docker DNS)
]
_cors_env = os.getenv("CORS_ORIGINS", "").strip()
_cors_origins = (
    [origin.strip() for origin in _cors_env.split(",") if origin.strip()]
    if _cors_env
    else _default_origins
)
app.add_middleware(
    CORSMiddleware,
    allow_origins=_cors_origins,
    allow_credentials=True,
    allow_methods=["*"],
    allow_headers=["*"],
)

# Request/response logging — logs method, path, status code and duration for
# every non-health request. See api/middleware.py for details.
app.add_middleware(RequestLoggingMiddleware)

# ── Prometheus metrics (Phase 4) ─────────────────────────────────────────────
# Instrumentator wraps every route and records histogram metrics:
#   http_requests_total, http_request_duration_seconds, etc.
# These are scraped by Prometheus at /metrics (added by .expose()).
Instrumentator().instrument(app).expose(app)

# ── Routes ───────────────────────────────────────────────────────────────────

# Include the two routers — each router prefixes its own routes
app.include_router(properties_router.router)
app.include_router(models_router.router)
app.include_router(images_router.router)


@app.get("/health", response_model=HealthResponse, tags=["health"])
def health_check() -> HealthResponse:
    """
    Liveness check used by Docker Compose health checks and load balancers.

    Returns:
        HealthResponse with overall status and individual component checks.
    """
    db_ok = check_db_connection()
    return HealthResponse(
        status="ok" if db_ok else "degraded",
        database="ok" if db_ok else "unreachable",
    )


@app.get("/", tags=["health"])
def root() -> dict[str, str]:
    """Redirect hint — the real API lives under /api/v1/ and docs at /docs."""
    return {
        "message": "Amenity Detector API is running.",
        "docs": "/docs",
        "health": "/health",
    }


# ── Local dev entrypoint ─────────────────────────────────────────────────────
# Run directly with: uv run python -m api.main
if __name__ == "__main__":
    import uvicorn

    uvicorn.run(
        "api.main:app",
        host="0.0.0.0",
        port=int(os.getenv("API_PORT", "8000")),
        reload=True,
    )
