"""
FastAPI application entrypoint.

How to run locally (without Docker):
    uv run uvicorn api.main:app --reload --port 8000

How to run in Docker Compose:
    docker compose up api
    # The app is then reachable at http://localhost:8000

API documentation (auto-generated by FastAPI):
    http://localhost:8000/docs   ← Swagger UI (interactive)
    http://localhost:8000/redoc  ← ReDoc (read-only)

Application lifecycle:
  startup:  Initialises the ModelRegistry (VLM clients) and creates DB tables.
            These are stored on `app.state` so routes can access them via Depends().
  shutdown: Disposes the SQLAlchemy engine (closes connection pool).
"""

import logging
import os
from contextlib import asynccontextmanager
from collections.abc import AsyncGenerator

from fastapi import FastAPI
from fastapi.middleware.cors import CORSMiddleware

from api.routers import models as models_router
from api.routers import properties as properties_router
from api.schemas import HealthResponse
from db.session import check_db_connection, create_tables
from models.registry import ModelRegistry

logging.basicConfig(
    level=logging.INFO,
    format="%(asctime)s  %(levelname)-8s  %(name)s — %(message)s",
)
logger = logging.getLogger(__name__)


# ── Lifespan ─────────────────────────────────────────────────────────────────
# FastAPI's modern way to run startup/shutdown logic (replaces @app.on_event).
# The `async with` block:
#   - Code before `yield` runs at startup
#   - Code after `yield` runs at shutdown
# The `app` argument lets us store state on `app.state` for dependency injection.

@asynccontextmanager
async def lifespan(app: FastAPI) -> AsyncGenerator[None, None]:
    """
    Manage application startup and shutdown resources.

    Why lifespan instead of @app.on_event?
      @app.on_event("startup") is deprecated in FastAPI 0.93+. The lifespan
      context manager is the official replacement — it's cleaner and supports
      async properly.

    Startup steps:
      1. Create database tables (idempotent — safe to run on every start).
         In production, `alembic upgrade head` (in the Dockerfile CMD) runs instead.
      2. Build the ModelRegistry from environment variables.
         Models that fail to initialise are logged as warnings — the server
         still starts even if, say, Ollama isn't running yet.
    """
    # ── STARTUP ──
    logger.info("Starting up Amenity Detector API...")

    create_tables()

    app.state.model_registry = ModelRegistry.from_env()
    available = app.state.model_registry.available_models()
    logger.info("Model registry ready. Available models: %s", available)

    yield  # Server is running — handle requests here

    # ── SHUTDOWN ──
    logger.info("Amenity Detector API shutting down.")


app = FastAPI(
    title="Amenity Detector API",
    description=(
        "Detect amenities in property images using Vision-Language Models. "
        "Upload images, browse properties, and search by amenity."
    ),
    version="1.0.0",
    lifespan=lifespan,
    docs_url="/docs",
    redoc_url="/redoc",
)

# ── CORS ────────────────────────────────────────────────────────────────────
# Allow the Gradio UI (Phase 3, port 7860) and local development to call the API.
# In production, restrict `allow_origins` to your actual domain.
app.add_middleware(
    CORSMiddleware,
    allow_origins=["*"],  # TODO Phase 5: lock down to specific origins
    allow_credentials=True,
    allow_methods=["*"],
    allow_headers=["*"],
)


# ── Routes ───────────────────────────────────────────────────────────────────

# Include the two routers — each router prefixes its own routes
app.include_router(properties_router.router)
app.include_router(models_router.router)


@app.get("/health", response_model=HealthResponse, tags=["health"])
def health_check() -> HealthResponse:
    """
    Liveness check used by Docker Compose health checks and load balancers.

    Returns:
        HealthResponse with overall status and individual component checks.
    """
    db_ok = check_db_connection()
    return HealthResponse(
        status="ok" if db_ok else "degraded",
        database="ok" if db_ok else "unreachable",
    )


@app.get("/", tags=["health"])
def root() -> dict[str, str]:
    """Redirect hint — the real API lives under /api/v1/ and docs at /docs."""
    return {
        "message": "Amenity Detector API is running.",
        "docs": "/docs",
        "health": "/health",
    }


# ── Local dev entrypoint ─────────────────────────────────────────────────────
# Run directly with: uv run python -m api.main
if __name__ == "__main__":
    import uvicorn

    uvicorn.run(
        "api.main:app",
        host="0.0.0.0",
        port=int(os.getenv("API_PORT", "8000")),
        reload=True,
    )